### ISSUE TITLE
The code is blank

### ISSUE THREAD

**Issue by farnetani** [ramsatt/Angular-4---Data-Table---File-Export#1]
The code is blank...Where is datatables implement?

**Comment by ramsatt** [comment]
Check Now

Sent from Mail for Windows 10

From: Arlei F. Farnetani Junior
Sent: Monday, October 30, 2017 3:50 PM
To: ramsatt/Angular-4---Data-Table---File-Export
Cc: Subscribed
Subject: [ramsatt/Angular-4---Data-Table---File-Export] The code is blank (#1)

The code is blank...Where is datatables implement?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
